research_task:
  description: >
    Conduct thorough research on DeFi projects that adhere to Ethical Principles, focusing on compliance with Shariah law in DeFi
    Make sure you find any interesting and relevant Projects running in mantel network given the current year is 2025.
  expected_output: >
    A list with 10 bullet points of the most relevant Projects running in mantel network with Ethical Finance Principles.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report on DeFi projects with Ethical Finance Principles.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
